from __future__ import annotations

import io

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

from models import FloorPlan


MARGIN = 50
DRAW_WIDTH = 500
DRAW_HEIGHT = 650


def _scale_point(x: float, y: float, plan: FloorPlan) -> tuple[float, float]:
    sx = DRAW_WIDTH / max(plan.width, 1)
    sy = DRAW_HEIGHT / max(plan.height, 1)
    scale = min(sx, sy)

    px = MARGIN + x * scale
    py = MARGIN + y * scale
    return px, py


def generate_floor_plan_pdf(plan: FloorPlan) -> bytes:
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)

    c.setTitle(f"{plan.name} - Floor Plan Export")
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, 760, f"{plan.name} - Permit Draft")
    c.setFont("Helvetica", 10)
    c.drawString(50, 744, f"Scale: 1 unit = {1/plan.scale.pixels_per_unit:.4f} {plan.scale.unit} (mock)")

    # Draw walls
    c.setLineWidth(2)
    for wall in plan.walls:
        x1, y1 = _scale_point(wall.start.x, wall.start.y, plan)
        x2, y2 = _scale_point(wall.end.x, wall.end.y, plan)
        c.line(x1, y1, x2, y2)

    # Draw rooms and labels
    c.setLineWidth(1)
    for room in plan.rooms:
        if len(room.polygon) < 3:
            continue

        first = room.polygon[0]
        x0, y0 = _scale_point(first.x, first.y, plan)
        c.setStrokeColorRGB(0.2, 0.2, 0.2)
        c.setFillColorRGB(0.95, 0.97, 1.0)

        path = c.beginPath()
        path.moveTo(x0, y0)
        for p in room.polygon[1:]:
            px, py = _scale_point(p.x, p.y, plan)
            path.lineTo(px, py)
        path.close()
        c.drawPath(path, stroke=1, fill=1)

        cx = sum(p.x for p in room.polygon) / len(room.polygon)
        cy = sum(p.y for p in room.polygon) / len(room.polygon)
        tx, ty = _scale_point(cx, cy, plan)
        c.setFillColorRGB(0.05, 0.05, 0.2)
        c.setFont("Helvetica", 9)
        c.drawCentredString(tx, ty, f"{room.name} ({room.area_sqft} sqft)")

    # Basic dimensions text block
    c.setFillColorRGB(0, 0, 0)
    c.setFont("Helvetica", 9)
    c.drawString(50, 45, f"Overall footprint: {plan.width:.1f} ft x {plan.height:.1f} ft")
    c.drawString(50, 32, "Generated by Makrly Floor Plan Backend (mock PDF export)")

    c.showPage()
    c.save()

    buffer.seek(0)
    return buffer.read()
